# Generated by Django 4.2.7 on 2023-12-01 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-id"]},
        ),
        migrations.DeleteModel(
            name="RelatedPost",
        ),
    ]
